title=QRBillius - Create QR Bills

addViewHeader=Add a new bill
exportViewHeader=Save bills
settingsViewHeader=Settings
accountSettingsHeader=Account Settings
importSettingsHeader=Import Settings

accountField=IBAN Account
nameField=Name
addressLine1Field=Address Line 1
addressLine2Field=Address Line 2
paymentAmountField=Amount
additionalInfoField=Additional Info
languageField=Language

wordTemplateField=Word Vorlage
csvSeparatorField=CSV Separator
nameFormatField=Name format
addressLine1FormatField=Address line 1 format
addressLine2FormatField=Address line 2 format
paymentAmountFormatField=Payment amount format
additionalInfoFormatField=Additional information format

cancelButton=Cancel
addButton=Add
saveButton=Save

allFileExtensions=All Files

openTooltip=Import bills
addTooltip=Add new bill
removeTooltip=Remove selected bill
exportTooltip=Save bills
settingsTooltip=Settings
