title=QRBillius - Create QR Bills

addSceneHeader=Add a new bill
settingsSceneHeader=Settings
accountSettingsHeader=Account Settings
accountField=IBAN Account
nameField=Name
addressLine1Field=Address Line 1
addressLine2Field=Address Line 2
paymentAmountField=Amount
additionalInfoField=Additional Info
languageField=Language

cancelButton=Cancel
addButton=Add
saveButton=Save

allFileExtensions=All Files

openTooltip=Import bills
addTooltip=Add new bill
removeTooltip=Remove selected bill
saveTooltip=Save bills
settingsTooltip=Settings
